# Generated by Django 3.1.7 on 2021-06-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_usersettings_show_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='about_user',
            field=models.CharField(blank=True, default=False, max_length=500, verbose_name='about user'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='send_email_updates_messages',
            field=models.BooleanField(default=False, verbose_name='send email updates messages'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='send_email_updates_threads',
            field=models.BooleanField(default=False, verbose_name='send email updates threads'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='send_email_updates_user_quests_reviews',
            field=models.BooleanField(default=False, verbose_name='send email updates user quests reviews'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='send_email_updates_user_reviews',
            field=models.BooleanField(default=False, verbose_name='send email updates user reviews'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='send_me_emails_with_news_from_project_alpha',
            field=models.BooleanField(default=False, verbose_name='send me emails with news from project alpha '),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(default='Europe/London', max_length=50, verbose_name='timezone'),
        ),
    ]
