# Generated by Django 3.1.7 on 2021-05-29 13:37

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_usersettings_show_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, validators=[django.contrib.auth.password_validation.validate_password], verbose_name='password'),
        ),
    ]
