# Generated by Django 3.1.7 on 2021-06-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20210609_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='avatar',
            field=models.FilePathField(blank=True, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='nickname_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='nickname_updated'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='show_email'),
        ),
    ]
