development:
  DEBUG: True
  SECRET_KEY: '4vjtf_9%ltt*pi7'
  ALLOWED_HOSTS:
    - 'localhost'
    - '127.0.0.1'
  CORS_ALLOWED_ORIGINS:
    - 'http://localhost:8000'
    - 'http://127.0.0.1:8000'
    - 'http://localhost:3000'
    - 'http://127.0.0.1:3000'