jobs:
  include:
    - language: python
      python: 3.9
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
      script: python manage.py test

    - language: node_js
      node_js: 14
      before_install:
        - cd frontend
      install:
        - npm i
      stage: frontend-unit-test
        - npm run test