version: '3'

services:
  django:
    container_name: django
    expose:
      - "8000"
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - "static:/usr/src/app/backend/static/dist"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes:
      - "static:/usr/src/app/backend/static/dist"

volumes:
  static: