# Generated by Django 3.1.7 on 2021-03-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='nickname'),
        ),
    ]
