# Generated by Django 3.1.7 on 2021-04-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210403_2248'),
        ('web', '0003_usersettings'),
    ]

    operations = [
    ]
