# Generated by Django 3.1.7 on 2021-04-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_merge_20210426_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='is_first_nickname_update',
        ),
    ]
