# Generated by Django 3.1.7 on 2021-04-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210426_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='show email'),
        ),
    ]
